- name: create a web file
  hosts: all
  ignore_errors: yes
  tasks:

    - name: Touch the same file
      ansible.builtin.file:
        path: /root/hwreport.txt
        state: touch

    
    - name: Touch the same file
      ansible.builtin.file:
        path: /root/hwreport1.txt
        state: touch

    - name: Copy using inline content
      ansible.builtin.copy:
        content: |
          #hwreport
          HOSTNAME= "{{ ansible_hostname }}"
          MEMORY= "{{ ansible_memtotal_mb }}"
          BIOS= " {{ ansible_bios_version }}"
          CPU= " {{ ansible_processor }}"
          DISK_SIZE= " {{ ansible_devices['nvme0n1']['size'] }}"
        dest: /root/hwreport.txt

          
    - name: Copy using inline content
      ansible.builtin.copy:
        content: |

          HOSTNAME= "{{ ansible_hostname | default ('NONE') }}"
          MEMORY= "{{ ansible_memtotal_mb }}"
          BIOS= " {{ ansible_bios_version }}"
          CPU= " {{ ansible_processor }}"
          DISK_SIZE= " {{ ansible_devices['nvme0n1']['size'] }}"
          DISK_SIZE= " {{ ansible_devices['nvme0n2']['size'] | default('NONE') }}"
        dest: /root/hwreport1.txt

